Block1 hw2 automata
grrrance/formal-lang-course pull request #2
Opened 2023-09-18 18:24 UTC by grrrance

# Задача 2. Построение детерминированного конечного автомата по регулярному выражению и недетерминированного конечного автомата по графу

- [x] Используя возможности [pyformlang](https://pyformlang.readthedocs.io/en/latest/) реализовать **функцию** построения минимального ДКА по заданному регулярному выражению. [Формат регулярного выражения.](https://pyformlang.readthedocs.io/en/latest/usage.html#regular-expression).
- [x] Используя возможности [pyformlang](https://pyformlang.readthedocs.io/en/latest/) реализовать **функцию** построения недетерминированного конечного автомата по [графу](https://networkx.org/documentation/stable/reference/classes/multidigraph.html), в том числе по любому из графов, которые можно получить, пользуясь функциональностью, реализованной в [Задаче 1](https://github.com/FormalLanguageConstrainedPathQuerying/formal-lang-course/blob/main/tasks/task1.md) (загруженный из набора данных по имени граф, сгенерированный синтетический граф). Предусмотреть возможность указывать стартовые и финальные вершины. Если они не указаны, то считать все вершины стартовыми и финальными.
- [x] Добавить необходимые тесты.

2023-09-21 20:40 UTC, rustam-azimov requested changes

2023-09-21 20:40 UTC, rustam-azimov commented on project/utils/automata_lib.py
> +    return regex.to_epsilon_nfa().to_deterministic().minimize()
Тут есть лишний вызов

2023-09-21 20:40 UTC, rustam-azimov commented on project/utils/automata_lib.py
> +    A non-deterministic automaton where epsilon transitions are allowed
Нужно ли позволять эпсилон переходы? Если да, то в каких случаях будут полезны?

2023-09-21 21:05 UTC, grrrance commented on project/utils/automata_lib.py
> +    return regex.to_epsilon_nfa().to_deterministic().minimize()
Убрано

2023-09-21 21:15 UTC, grrrance commented on project/utils/automata_lib.py
> +    A non-deterministic automaton where epsilon transitions are allowed
Эпсилон переходы допустимы, когда нет метки между двумя вершинами, то есть допустим переход из пустой(эпсилон) строки, чтобы автомат переводить в оба состояния одновременно. Может быть полезен, когда текущее состояние в точности неизвестно. Эпсилон переходы убраны.

2023-09-22 14:41 UTC, rustam-azimov approved these changes

2023-09-22 14:44 UTC, merged